### ISSUE TITLE
Resolve sample mapping from QIIME artefacts to existing samples

### ISSUE THREAD

**Issue by alexmanuele** [mwhall/QUOREM#27]
QIIME seems to replace underscores with dashes when creating sample id. 
This prevents samples from mapping properly during upload.

**Comment by mwhall** [comment]
This sounds about right. The underscores are specials used at a few points in QIIME2, particularly in filenames. It's not really easy to figure out which of the dashes are real dashes, and which are former underscores.

What's the order of operations here? Are you registering the samples before uploading the artifacts? It should be registering the Samples with the modified names, so you should be getting 2x the number of Samples you expect.

If we can't resolve this reliably every time a user uploads an artifact without them telling us which dashes need to be underscores, I think the solution is to set the underscored names as upstream Samples of the dashed names.

**Comment by alexmanuele** [comment]
I observed this from first uploading spreadhseets containing samples + metadata, etc, and then uploading qiime artifacts. This does result in duplicate samples.
so a sample with name "20190814_118_G002_UI593_NMR_PresDay0S7_3" becomes "20190814-118-G002-UI593-NMR-PresDay0S7-3".

It should be a possible task to change some part of the workflow or other to either recognise dashes/underscores interchangeably or else to force the use of one or the other- Will look into it this week

**Comment by mwhall** [comment]
This is probably the primary source.

Currently, I scrape the Sample names from an artifact by searching backwards through the provenance to find the artifact that contains the source import with a MANIFEST file. We're not guaranteed to have the *actual* MANIFEST file, since it's probably not the import file itself we're looking at, so we just scrape the action.yaml which contains the filenames and their md5sums. By convention, the first portion of the filenames are the sample id. If I could get the *actual* MANIFEST file in the import artifact, I know how these relate and can make that link. But until we get that file, we don't really know what the sample ids are.

I wonder if there's anywhere else in the provenance I can find the sample ids...

**Comment by mwhall** [comment]
I dunno, I know these files pretty intimately by now. I don't think there's a way to recover that link that relates the sample_ids to the first bit of the filenames they were imported from without the sequences artifact that contains the MANIFEST file itself. None of the .yaml seem to capture it.

It might have to be sufficient to automatically make that link when the import artifact is uploaded, and inform and help users make that link if it isn't uploaded. In this case, that just means putting in a spreadsheet with the names scraped by QUOR'em (with underscores) as the sample_id values and an upstream column with the dashed names.

**Comment by alexmanuele** [comment]
Closing issue as this seems to be a user input problem rather than a programmatic one - close inspection of artefacts showed that the manifest file and metadata file used different sample names, which obviously cant be resolved automatically.
